// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejxmppkqpbrrizsiqrgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqeG1wcGtxcGJycml6c2lxcmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODQ3NDksImV4cCI6MjA3MDE2MDc0OX0.bxR8QD4mjvYd7sR6jymLxt1m2_wMprF8F3GfQ6UFX6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});